name: kenya_events_hub
description: Discover, share, and attend events across Kenya.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  shared_preferences: ^2.2.3
  cloud_firestore: ^5.5.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.2
  google_maps_flutter: ^2.7.0
  geolocator: ^13.0.1
  url_launcher: ^6.3.0
  share_plus: ^10.0.2
  intl: ^0.19.0
  animations: ^2.0.11
  cached_network_image: ^3.3.1
  http: ^1.2.2
  package_info_plus: ^8.1.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
